# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96cbf7d97cf37b6e40320e420969e17aac3a5af9130585eaea85d06905b35727d28e9a8eed35a10067f1009c81ea6e0d5c45c646a8ccc513c2e94ece51d7d60a

test:
  secret_key_base: 4b2642c3d1482ff665d2c9bbdb719369552f6a4ba7070fe3cc2a41c3e46e590629fd51f36029bde4ea5dcefb6c52e9ad2378a8d9a9260699dd2c4044a2ad100a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
